Resources/Prototypes/Maps/plasma.yml

Изменено число должностей на карте.
Потому что баланс
- Уменьшено число детективов до 1, утилизаторов до 3, парамедика до 1 на Plasma Station

Изменение должностей на Plasma Station

---

Content.Shared/Doors/Components/DoorComponent.cs
Content.Shared/Doors/Systems/SharedAirlockSystem.cs
Content.Shared/Doors/Systems/SharedDoorSystem.cs

This reverts commit 7c4c77a881e54bef4758e25d5e480de589c3fd5a.
Хот-ревёрт пока не будет понятно что не так
https://discord.com/channels/1030160796401016883/1341520194266206228
https://discord.com/channels/1030160796401016883/1341543014463443024

Revert "Исправление закрытия шлюзов без питания (#2)"

---

Resources/Prototypes/Maps/silly.yml

Закомментил роль психолога
Пока нет кабинета психолога, проще удалить эту роль
:cl:
- tweak: Удалена роль психолога на Silly Island.

Изменение должности на Silly Island

---

Resources/Prototypes/Maps/reach.yml

Добавлены роли на Рич
Фенриз ремапнул Рич под мк сборку, добавив спаунеры ведущих ролей и командования, так что добавил и сами роли
По сути, раз уж добавили роли командования и ведущих, то надо и в прототип это занести, а так же добавил осщ, раз уж главы появились
Немного отсортировал роли в прототипе, для удобства
:cl:
- add: Добавлены роли командования и ведущие роли для Reach Transport.

Изменение должностей на Reach Transport

---

Content.Client/Lobby/UI/ServerListBox.cs

Added link to new server

---

Content.Client/Chemistry/UI/TransferAmountBoundUserInterface.cs
Content.Shared/Chemistry/EntitySystems/SharedInjectorSystem.cs
Resources/Prototypes/Entities/Objects/Specific/chemistry.yml

Transfer amount UI for injector component

---

Resources/Prototypes/Entities/Clothing/Shoes/boots.yml

Add ClothingSlowOnDamageModifier for combat boots

---

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml

Добавил двоичный ключ шифрования в шкафчик научного руководителя
По предложке ([ссылка](https://discord.com/channels/1030160796401016883/1342836439016275998))
Просто добавил ID ключа шифрования в заполненный шкафчик науч. рука
нема
:cl:
- add: Добавлен двоичный ключ шифрования в шкаф научного руководителя.

Двоичный ключ шифрования научному руководителю

---

Resources/Locale/ru-RU/ss14-ru/prototypes/_corvax/entities/clothing/outerclothing/vests.ftl
Resources/Prototypes/Catalog/Fills/Lockers/security.yml
Resources/Prototypes/Catalog/Fills/Lockers/wardrobe_job.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
Resources/Prototypes/Entities/Markers/Spawners/Random/Department/security.yml
Resources/Prototypes/Loadouts/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Fun/visitors_startinggear.yml
Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml

Замена ClothingOuterArmorBasic на ClothingOuterVestArmorSec (Корваксный бронежилет который мы никогда не использовали, но респрайтнули) в арсенале СБ.

Swap sec armor vest

---

Resources/Prototypes/Entities/Effects/puddle.yml

Фикс следов.
Mne vinesli mozg.
This can be easily fixed, right?
Add TimedDespawn component for footsteps.
:cl:
- fix: Следы теперь сами деспавнятся спустя 600 секунд.

Footsteps hotfix

---

Resources/Prototypes/_DeadSpace/Entities/Objects/Tools/tools.yml

Значительно увеличено время автоматического пополнения зарядов в РСУ СИ.
:cl:
- tweak: РСУ СИ теперь восстанавливает один заряд раз в 2 минуты, вместо 10 секунд.

Tweak RCD CE auto recharge time

---

Content.Server/DeadSpace/HardsuitIdentification/HardsuitIdentificationComponent.cs
Content.Server/DeadSpace/HardsuitIdentification/HardsuitIdentificationSystem.cs

Добавление нелетального вида привязки скафа.
Теперь к   - type: HardsuitIdentification можно приписать nonlethal: true

Добавлен параметр nonlethal в HardsuitIdentification

---

Content.Shared/Atmos/Atmospherics.cs
Resources/Prototypes/Atmospherics/gases.yml

Бафф атмоса, теперь фрезон продаётся за 3 кредита.
В ходе того, что атмосы совсем перестали использовать доступные им механики по варке газов и их конденсации, я думаю, что упрощение варки газов станет достаточным поводом для мотивации здешних атмосов снова начать постигать данные им механики, тем более визарды пока не планируют добавлять новый контент для атмосферного отдела, так как код атмоса, в их понимании, надо полностью рефакторить.
Поменял значения, описанные выше.
:cl:
- add: Теперь фрезон увеличился в цене за 1 моль до 3 кредитов.

Увеличение цены фрезона за моль

---

Resources/Prototypes/_DeadSpace/Sponsor/kelic.yml

Добавил функции мед.визора для очков и инструмент синтезатор в наборе доминатора Kelic

Tweak Kelic sponsor kit

---

Content.Server/Backmen/FootPrint/FootPrintsSystem.cs
Resources/Prototypes/Entities/Effects/puddle.yml

Теперь следы не спавнятся при высокой нагрузке на сервер + оптимизация.
:cl: Kayzel, trest100
- tweak: Выполнена дополнительная оптимизация следов.

[FIX] FootSteps OnMove rework

---

Resources/Prototypes/_DeadSpace/Entities/Objects/Consumable/Food/food.yml

Исправил деление на 12 частей -> теперь 4 части. Не знаю как провтыкал/не сохранил изменение до этого
Надо чинить.
Изменил одно значение в прототипе
Нет
Нет
:cl:
- fix: Мегасэндвич теперь делится на 4 частей, а не на 12.

Фикс мегасэндвича

---

Content.Server/Database/ServerDbBase.cs
DeadSpace/Content.DeadSpace.Interfaces.Client/IClientSponsorsManager.cs
DeadSpace/Content.DeadSpace.Interfaces.Server/Content.DeadSpace.Interfaces.Server.csproj
DeadSpace/Content.DeadSpace.Interfaces.Server/IServerChatFilter.cs
DeadSpace/Content.DeadSpace.Interfaces.Server/IServerPlayTimeManager.cs
DeadSpace/Content.DeadSpace.Interfaces.Server/IServerSponsorsManager.cs
DeadSpace/Content.DeadSpace.Interfaces.Shared/ISharedSponsorsManager.cs

Add support of secret (not so) playtime server and interfaces small cleanup

---

Resources/Prototypes/Maps/amber.yml

Добавлена роль пилота СБ
Пилот СБ есть, но роль не завезли
:cl:
- tweak: Добавлена роль пилота СБ на Amber.

Add sec pilot to Amber Station

---

Content.Server/DeadSpace/MutilatedCorpse/MutilatedCorpseComponent.cs
Content.Server/DeadSpace/MutilatedCorpse/MutilatedCorpseSystem.cs
Resources/Locale/ru-RU/_deadspace/prototypes/entities/mobs/species/mutilated_corpse.ftl
Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
Resources/Prototypes/Entities/Mobs/Species/diona.yml
Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
Resources/Prototypes/Entities/Mobs/Species/human.yml
Resources/Prototypes/Entities/Mobs/Species/moth.yml
Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
Resources/Prototypes/Entities/Mobs/Species/vox.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/demon.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/felinid.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/kobalt.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/shark.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/tajaran.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/vulpkanin.yml

> По итогу что бы это не выглядело слишком жестоко в нашей очень доброй игре, думаю можно это просто привязать к режущему урону и если его больше условных 200 единиц, то персонаж превращается в неопознанного (а ещё тогда в этой ситуации наверное стоит неопознанные трупы переименовать просто в "неопознанный") и если меньше то возвращает своё старое имя. На счёт меты думаю что это не будет сильная проблема так как нормой станет проверка всех трупов и люди будут ждать что это труп игрока. И от замены ДНК полностью стоит отказаться. 
Переименовывать труп не стал
Кто же знал, что самое сложное в этой задаче будет форкунтся и залить пр :aga:
Новый компонент, новая система.
:cl:
- add: Теперь труп многих рас невозможно опознать при большом уроне порезов.

Mutilated corpse

---

Content.Server/Research/Systems/ResearchSystem.Client.cs
Content.Server/Research/Systems/ResearchSystem.cs

Исправляет ошибку связанную с видимостью таймпаном сервера станции
Добавил просто фильтрацию через MapID при начальном выборе сервера
:cl: a+w.exe
- fix: Теперь тайпан не может использовать РНД сервер станции НТ

Fix global RND servers

---

Content.Shared/Ensnaring/SharedEnsnareableSystem.cs

Исправление бага https://discord.com/channels/1030160796401016883/1164223291259625532/1368927094473490553
Костыль до решения со стороны виз репы.
:cl: a+w.exe
- fix: Исправлен Баг связанный с болой и космической смазкой

[HOTFIX] Lubed bola

---

Resources/Prototypes/Objectives/traitor.yml

Отмена уникальности цели убийства предателя.
Попросили для ивентов и того подобного.
Просто false поставил.

Отмена уникальности убийству треитора

---

Content.Client/Lobby/UI/ServerListBox.cs

Фикс бага разного перехода серверов
Баг
На локалке не затестить, выдаёт ошибку при попытке перехода на другой сервер
не требуется
:cl:
- fix: Фикс бага перехода серверов!

Фикс перехода серверов

---

Resources/Prototypes/Body/Organs/Animal/animal.yml
Resources/Prototypes/Body/Organs/human.yml
Resources/Prototypes/_DeadSpace/Body/Organs/ipc.yml
Resources/Prototypes/_DeadSpace/Body/Organs/xenomorph.yml

Добавлен тэг "Trash" всем видам органов - теперь они спокойно помещаются в мусорный мешок.
По предложению https://discord.com/channels/1030160796401016883/1320136192733483098
На баланс не влияет, упрощает жизнь уборщикам.
Изменены все базовые прототипы органов - им добавлен дополнительный тэг.
Не требуется.
Нет.
:cl:
- tweak: Органы теперь можно собрать в мусорный мешок.

Возможность собрать органы в мусорный мешок

---

Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
Resources/Prototypes/Entities/Mobs/Species/diona.yml
Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
Resources/Prototypes/Entities/Mobs/Species/human.yml
Resources/Prototypes/Entities/Mobs/Species/moth.yml
Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
Resources/Prototypes/Entities/Mobs/Species/slime.yml
Resources/Prototypes/Entities/Mobs/Species/vox.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/computer.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/demon.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/felinid.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/kobolt.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/shark.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/tajaran.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/vulpkanin.yml
Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/xenomorph.yml

:cl:
- remove: Следы временно отключены.

Temp disable FootPrints

---

Resources/Maps/barratry.yml
Resources/Maps/core.yml
Resources/Maps/elkridge.yml
Resources/Maps/gemini.yml
Resources/Maps/saltern.yml

Fix map file schema validator

---

Content.IntegrationTests/Tests/PostMapInitTest.cs
Resources/Prototypes/Maps/Pools/default.yml

Return Elkridge to map pool

---

Resources/Prototypes/Catalog/uplink_catalog.yml
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml
Resources/Prototypes/Loadouts/Jobs/Security/security_cadet.yml
Resources/Prototypes/Loadouts/Jobs/Security/security_officer.yml

Пониженна стоимость голопаразита с 14 до 12(скидку не трогал)
Добавил рубашки в лодаут сб(и для гсб тоже, но не для офицера она у него вроде и так есть...)
Синдикота теперь можно брать на руки(при поднятии занимает две руки) и класть в сумку
:cl:
- add: Добавлена возможность поднимать синдикота на руки 
- add: добавлены в лодауты сб добавлены рубашки 
- tweak: Изменена цена на голопаразита 12 тк

Пониженна цена голопоразита, докинул рубашки в лодаут сб

---

Content.Server/DeadSpace/ShowRevolutionIcon/ShowRevolutionIconSystem.cs
Content.Shared/DeadSpace/ShowRevolutionIcon/ShowRevolutionIconComponent.cs
Content.Shared/Revolutionary/SharedRevolutionarySystem.cs
Resources/Prototypes/StatusIcon/faction.yml

Теперь иконку революционеров видно всем на второй стадии революции.
По таску
:cl: a+w.exe
- add: Теперь революционеров видно во второй стадии.

Show revolution icon 

---

Resources/Maps/meta.yml

Добавлено платные: одеждомат, зимнешкаф, плащвенд.
Добавлено фулл комплект клонерки.
Добавлено хранилище скафандра инструктора.

[MAPS] Meta and Origin update

---

Resources/Prototypes/_DeadSpace/Sponsor/sil.yml

По просьбе спонсора добавил нелетальный биокод скафу. При надевании пишет о несовпадении ДНК и сбрасывает на пол
По просьбе - https://discord.com/channels/1030160796401016883/1376165788209381448
Добавил две строки в прототип скафа - компонент биокода
Не требуется
Нет
Они не должны знать

Биокод для спонсорского скафа Sil

---

Resources/Prototypes/Entities/Objects/Consumable/Smokeables/base_smokeables.yml

Добавил возможность извлечения реагентов из сигарет через измельчитель.
На данный момент в сигареты можно вводить вещества, но возможность их получить обратно отсутствует. Это показалось мне недоработкой. Добавляет возможность профессиям, не имеющим прямого доступа к химикатам (Шеф-повар, Бармен, Сервисный ассистент), получить их из сигарет (например, железо, ликоксид, сварочное топливо, ТГК) для разнообразия меню или злодейских планов.
Не требуются
:cl:
- add: Добавлена возможность извлечения веществ из сигарет

Добавлена возможность извлечения веществ из сигарет

---

Resources/Prototypes/Entities/Objects/Shields/shields.yml

Возвращает визардские значения прочности щитов.
Мета щитов сейчас очень сильна, ради эксперимента значительный нёрф щитов.
:cl:
- tweak: Значения прочности щитов понижено до визардских значений, все щиты потеряли от 70% до 90% прочности.

Nerf shields

---

Content.Shared/Physics/CollisionGroup.cs

Убирает у предметов колизию к блобу, чтобы можно было кидать гранаты во внутрь блоба
Блоб стал сильнее изза анробастности мкашников, это хоть както сгладит углы
Удалены строки с маски айтемов о колизии с блобом

Update collision group

---

Resources/Prototypes/_Backmen/Entities/Mobs/NPC/blob.yml

Блобернауту добавлено ночное зрение
https://discord.com/channels/1030160796401016883/1394890082665627688
--
--
--
:cl:
- add: Блобернауту добавлено ночное зрение.

NightVision for blob

---

Resources/Prototypes/Recipes/Lathes/Packs/science.yml
Resources/Prototypes/Recipes/Lathes/Packs/tiles.yml
Resources/Prototypes/Research/civilianservices.yml
Resources/Prototypes/_DeadSpace/Entities/Objects/Misc/tiles.yml
Resources/Prototypes/_DeadSpace/Recipes/Lathes/tiles.yml

Или из-за невнимательности, или из-за кривого исправления мёрдж-конфлита новые рецепты отсутствовали в резательном станке. Исправил, адекватно отсортировал оффовские и наши тайлы. Добавил астро-траву в изучения. Теперь всё работает как надо
Исправление своего же косяка
Добавил в оригинальные паки новые тайлы, астро траву 
Не требуется
Нет
:cl:
- fix: Рецепты новых тайлов теперь присутствуют в резательном станке.

Хотфикс рецептов новых тайлов

---

Resources/Prototypes/Maps/amber.yml
Resources/Prototypes/Maps/fland.yml
Resources/Prototypes/Maps/gemini.yml
Resources/Prototypes/Maps/loop.yml
Resources/Prototypes/Maps/oasis.yml

На гемини, эмбере, лупе, оазисе и фланде уменьшено число парамедиков до 1
Второй парамедик не нужен, так как шкаф для второго парамедика давным давно удалён, а роль осталась

Уменьшение ролей парамедиков

---

Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml

Микро изменение прототипа роли мага, не затрагивающее ничего, кроме самого прототипа
Более корректная локализация будет после апстрима почти сразу
Изменена роль на вики, нужно менять и в игре. По просьбе куратора вики
https://discord.com/channels/1030160796401016883/1318968577570898012/1409533266926633062
Изменил один прототип Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
Добавил правила свободного агента (ибо вылазят базовые "ну имя не помнишь короче"
Не надо
Нет
:cl:
- tweak: Внутриигровые правила мага обновлены - теперь он свободный агент.

Маг - свободный агент (для соответствия роли на вики)

---

Resources/Prototypes/_DeadSpace/Entities/Mobs/Species/computer.yml

Потерялись тэги, нашёл и отвёл домой
Так надо
Код не трогал
Не надо
Нет
Микрофикс в 4 строки, не надо

Микро фикс КПБ/С

---

Resources/Maps/packed.yml

поменял варпоинты на русский язык, поставил платные одеждоматы, консоль крим записей в допроску

[MAPS] Packed update

---

Resources/Prototypes/_DeadSpace/Sponsor/reimon.yml
Resources/Prototypes/_DeadSpace/Sponsor/whoto.yml
Resources/Textures/_DeadSpace/Sponsor/qu0565/backpack.rsi/meta.json
Resources/Textures/_DeadSpace/Sponsor/qu0565/belt.rsi/meta.json
Resources/Textures/_DeadSpace/Sponsor/qu0565/hardsuit.rsi/meta.json
Resources/Textures/_DeadSpace/Sponsor/qu0565/helmet.rsi/meta.json
Resources/Textures/_DeadSpace/Sponsor/qu0565/jetpack.rsi/meta.json

По просьбе автора подредачил копирайт в указанных файлах, сменил резисты на актуальные значения 
По просьбе
Код не затронут
Не надо
Нет
Не надо

Изменение резистов и копирайта спонсоров

---

Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
Resources/Prototypes/Entities/Structures/Walls/walls.yml

Walls and airlocks small HP rebalance

---

Content.Server/Communications/CommunicationsConsoleSystem.cs

Tweak comms console TTS

---

Resources/Prototypes/_DeadSpace/Voice/speech_emotes.yml

Fix emotes blacklists

---

Content.Client/Corvax/TTS/TTSSystem.cs
Content.Server/DeadSpace/Necromorphs/InfectionDead/NecromorfSystem.Transform.cs
Content.Shared/DeadSpace/CCCCVars/CCCCVars.cs

Three small fixes

---

Content.Client/PDA/PdaMenu.xaml
Content.Client/PDA/PdaMenu.xaml.cs
Content.Server/PDA/PdaSystem.cs
Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
Content.Shared/PDA/PdaUpdateState.cs
Resources/Locale/ru-RU/pda/pda-component.ftl

Теперь в КПК будет отображаться время до прилета эвака и отлёта эвака.
По предложке.
:cl:
- add: Теперь время до прилёта эвака, есть в КПК!

Время до эвака в КПК

---

Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
Resources/Prototypes/Entities/Mobs/Species/moth.yml

Теперь пестициды наносят урон арахнидам и молям
Из предложки
:cl:
- add: Пестициды теперь наносят кислотный урон Арахнидам и Нианам.

Изменение пестицидов
