dead-space-server/space-station-14-fobos

- Content.Shared/Doors/Components/DoorComponent.cs
- Content.Shared/Doors/Systems/SharedAirlockSystem.cs
- Content.Shared/Doors/Systems/SharedDoorSystem.cs
Исправлен баг, что нельзя закрыть шлюз без питания (ломом или руками).
Баг, что нельзя закрыть шлюз без питания:
https://github.com/space-wizards/space-station-14/issues/33795
https://discord.com/channels/1030160796401016883/1333467066019090513/1333467066019090513
Взят этот PR https://github.com/space-wizards/space-station-14/pull/33968, в котором в `DoorComponent` добавлено поле `IsBeingPried` (подвергается ли дверь "силовому" воздействию) и проверки, что состояние шлюза можно изменить, когда нет питания и дверь изменяют силой (`!component.Powered && isBeingPried`).
От себя: проверил, пофиксил ([мои изменения](https://github.com/dakone22/space-station-14-fobos/compare/194f8eb42610a2ec3a9443d039510a078b441039...fb6bc8da74d4217729fa23507f81979131f362ef)) баг, что нет проверок на коллизии …
> Исправление закрытия шлюзов без питания

- Resources/Prototypes/_DeadSpace/Entities/Other/ertloadouts.yml
Матеба и N1984 поменялись местами в лодаутах ОБР. Матеба теперь у Гаммы, N1984 у Красного.
Попробовал сам, послушал мнения в предложении https://discord.com/channels/1030160796401016883/1340097111307456672/1340097111307456672. 
Точность Матебы - серьёзное преимущество перед N1984. Значит логически, она должна быть у отряда получше.
Поменялись местами айди предметов в лодаутах.
Нет.
:cl:
- tweak: Матеба и N1984 поменялись местами в лодаутах ОБР. Матеба перешла к Гамме, N1984 к Красному. https://discord.com/channels/1030160796401016883/1340097111307456672/1340097111307456672
> Рокировка Матебы и Кольта в лодаутах

- Content.Server/Speech/EntitySystems/OwOAccentSystem.cs
Убрана автозамена !! на смайлики (OwO и тд.)
Неуместные смайлики в разговоре, при которых не возможно кричать. Реализация предложки https://discord.com/channels/1030160796401016883/1340586443277336596
Просто убран лист смайликов и автозамена !! на них
Нет
> Убрана автозамена !! на OwO и тд

- Content.Shared/Doors/Components/DoorComponent.cs
- Content.Shared/Doors/Systems/SharedAirlockSystem.cs
- Content.Shared/Doors/Systems/SharedDoorSystem.cs
- Content.Shared/Doors/Systems/SharedFirelockSystem.cs
Исправлен баг, что нельзя закрыть шлюз без питания (ломом или руками).
Баг, что нельзя закрыть шлюз без питания:
https://github.com/space-wizards/space-station-14/issues/33795
https://discord.com/channels/1030160796401016883/1333467066019090513/1333467066019090513
Взят этот PR https://github.com/space-wizards/space-station-14/pull/33968, в котором в `DoorComponent` добавлено поле `IsBeingPried` (подвергается ли дверь "силовому" воздействию) и проверки, что состояние шлюза можно изменить, когда нет питания и дверь изменяют силой (`!component.Powered && isBeingPried`).
От себя: проверил, пофиксил ([мои изменения](https://github.com/dakone22/space-station-14-fobos/compare/194f8eb42610a2ec3a9443d039510a078b441039...fb6bc8da74d4217729fa23507f81979131f362ef)) баг, что нет проверок на коллизии …
> Исправление закрытия шлюзов без питания (ещё раз)

- Resources/Prototypes/_DeadSpace/Demons/demons.yml
Небольшой бафф демонов, общее кол-во крови увиличено на 33 процента(150 --》200)
Добавлено пассивное восстановление крови по 2 единицы за каждое обновление кровотечения то бишь если за одно обновление ты вытекал на 8 единиц крови то теперь будешь на 2 единицы фиксированно меньше
Что бы не так быстро вытекали от кровотёка. Ну и предложка.
2 строки кода в паренте демонов
Не нуждается
нету.
:cl:
- add: Уменьшено кровотечение у демонов.
> Бафф демонов

- Resources/Prototypes/Loadouts/role_loadouts.yml
Это невероятно, но в этом pr-e вернул значок юристам в стартовое снаряжение (он и был, просто закомментирован)
По предложке [ссылка](https://discord.com/channels/1030160796401016883/1342934827707404338)
Убрал комментарий в стартовом снаряжении юриста
нема
:cl:
- add: Юристы вновь могут выбрать значок юридического департамента в стартовом снаряжении.
> Значок юридического департамента юристам

- Resources/Locale/en-US/ss14-ru/prototypes/gamerules/unknown_shuttles.ftl
- Resources/Locale/ru-RU/ss14-ru/prototypes/gamerules/unknown_shuttles.ftl
- Resources/Prototypes/GameRules/unknown_shuttles.yml
- Resources/Prototypes/Shuttles/shuttle_incoming_event.yml
Добавил шаттл каперов в пул рандомных шаттлов как, например, странствующие шеф-повары или клоуны
По предложке ([ссылка](https://discord.com/channels/1030160796401016883/1341439145926725733))
В уже существующие файлы добавил новый путь, а так же локализацию. Так же сделал само появление шаттла безвучным, что, как по мне, будет лучше. Стоило ли добавлять комментарии вида `#DS14` к новым прототипам или надо переместить в папку DeadSpace/... ?
нема
:cl:
- add: Пираты возвращены как мидраунд антагонисты.
> Добавление шаттла пиратов в пул случайных шаттлов

- Resources/Prototypes/Maps/Corvax/astra.yml
- Resources/Prototypes/Maps/Corvax/avrite.yml
- Resources/Prototypes/Maps/Corvax/delta.yml
- Resources/Prototypes/Maps/Corvax/paper.yml
- Resources/Prototypes/Maps/Corvax/spectrum.yml
- Resources/Prototypes/Maps/amber.yml
- Resources/Prototypes/Maps/bagel.yml
- Resources/Prototypes/Maps/barratry.yml
- Resources/Prototypes/Maps/box.yml
- Resources/Prototypes/Maps/cluster.yml
- Resources/Prototypes/Maps/cog.yml
- Resources/Prototypes/Maps/convex.yml
- Resources/Prototypes/Maps/core.yml
- Resources/Prototypes/Maps/elkridge.yml
- Resources/Prototypes/Maps/fland.yml
- Resources/Prototypes/Maps/gemini.yml
- Resources/Prototypes/Maps/marathon.yml
- Resources/Prototypes/Maps/meta.yml
- Resources/Prototypes/Maps/oasis.yml
- Resources/Prototypes/Maps/omega.yml
- Resources/Prototypes/Maps/origin.yml
- Resources/Prototypes/Maps/packed.yml
- Resources/Prototypes/Maps/plasma.yml
- Resources/Prototypes/Maps/saltern.yml
- Resources/Prototypes/Maps/silly.yml
Были изменены требования минимального/максимального онлайна у большинства карт.
Требуемые значения были обговорены со старшим маппером. Сделано для улучшения подбора карт и большей вариативности этих самых карт. Аврит имел ограничение на онлайн, так что на хайпопе не мог выпасть, как пример.
Были изменены значения онлайна в оригинальных прототипах карт, местами удалены/добавлен maxPlayers.
Не требуется.
Нет.
:cl:
- tweak: Изменены требования онлайна для подбора большинства карт. Теперь вариативность их выпадения должна быть выше при любом онлайне.
> Исправление требуемого онлайна карт

- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/GameRules/meteorswarms.yml
- Resources/Prototypes/GameRules/unknown_shuttles.yml
Исправлено, а местами и добавлено требование конкретного числа игроков для геймрула:
AnomalySpawn - 10, GameRuleSpaceDustMinor - 5, GameRuleSpaceDustMajor - 10, GameRuleMeteorSwarmMedium - 20, GameRuleMeteorSwarmLarge - 25, GameRuleUristSwarm (???) - 25, UnknownShuttleInstigator - 45, UnknownShuttleManOWar - 35. 
Для более комфортной игры на лоупопе. Вражеские шаттлы не имели ограничений на спавн, поэтому появлялись и при 7 людях, и при 47. Для них выла выбрана золотая середина (LoneOps - 40, от него и отталкивался), чтобы это было интересно и не портило игрокам ночные смены. Это же и касается геймрулов метеоров, здесь отталкивался от GameRuleMeteorSwarm - 25, чтобы при отсутствии инженеров на ночных сменах игрокам чуть легче жилось. Ну и затронул спавн аномалии, чтобы не появлялась при …
> Исправление требований к количеству игроков у геймрулов

- Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
- Resources/Prototypes/Entities/Objects/Tools/bucket.yml
- Resources/Prototypes/_ADT/Entities/Objects/Consumable/Drinks/cup_and_teapot.yml
Изменён размер кувшинов для напитков - теперь они равны химическим, 2х4. Уменьшен объём некоторых кувшинов до стандартных 200 (300->200), но взамен увеличен объём пустого кувшина для напитков до 200 (150->200). Добавлена разрушаемость ведру - теперь оно не защищает содержимое от взрывов, ломается от нескольких ударов ломом (25 прочности) с характерным металлическим звуком, разливая содержимое и оставляя на своём месте сломанное ведро (мусор с обломков).
После увеличения ведра для льда и шейкера, некоторые игроки стали использовать огромные (150-300!!!) кувшины для напитков, что занимают всего 2х2. Либо ведро, что имеет ёмкость 250 при размере 2х2, ещё и защищает от взрывов. Все эти недостатки были исправлены в угоду балансу и использованию менее популярных, профильных ёмкостей …
> Фикс кувшинов для напитков и ведра

- Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/box.yml
Исправлен размер инвентаря хэппи хонков (2х4) и максимально допустимый размер предмета внутри. Повышен размер обычных нюка-хонков, теперь они равны заполненным едой (3Х5)
Зачастую хэппи хонки используются как дополнительные 16 слотов инвентаря, при этом занимают они всего 6 и стоят 50 копеек. Отныне они будут использоваться по назначению - поварами, а не ОСЩ для хранения магазинов к дрозду
Изменён файл \Prototypes\Entities\Objects\Consumable\Food\Containers\box.yml
Не требуется
Критических изменений нет, кроме ограничения по размеру предмета внутри (Normal->Small), а так же уменьшения размера внутреннего хранилища
:cl:
- tweak: Изменена вместимость хэппи хонков - теперь она равна обычной аптечке (2х4). Все нюка-хонки имеют повышенный размер хранилища.
> Лёгкое исправление инвентарей хэппи хонков

- Content.Server/DeadSpace/Abilities/Felinid/HairballComponent.cs
- Content.Server/DeadSpace/Necromorphs/InfectionDead/InitialNecroficationSystem.cs
- Content.Server/DeadSpace/Races/FelinidSystem.cs
- Content.Server/GameTicking/Rules/SpiderTerrorRuleSystem.cs
- Content.Shared/DeadSpace/Necromorphs/InfectionDead/Components/InitialNecroficationComponent.cs
- Resources/Prototypes/_DeadSpace/Spiders/cocoon.yml
- Resources/Prototypes/_DeadSpace/Spiders/gamerule.yml
- Resources/Prototypes/_DeadSpace/Spiders/princess.yml
- Resources/Prototypes/_DeadSpace/Spiders/queen.yml
Изменение для феленидского шара: сделал атрибут шанса на рыготу в компоненте, а не в самой системе.
Убрал эс из пауков ужаса , теперь вместо эс. прилетает доп. ОППУ.
Изменил название события инициации некрофикации.
Комок шерсти: для более гибкой настройки.
Убрал эс из пауков ужаса: по просьбе из-за изменений правил вызова эскадрона смерти.
Изменил название события инициации некрофикации: чтобы название было более понятным.
D:\space-station-14-fobos\Content.Server\DeadSpace\Abilities\Felinid\HairballComponent.cs
добавил ReadWrite атрибут: VomitChance 
D:\space-station-14-fobos\Content.Server\DeadSpace\Races\FelinidSystem.cs
атрибут VomitChance поместил в систему FelinidSystem.
D:\space-station-14-fobos\Content.Server\GameTicking\Rules\SpiderTerrorRuleSystem.cs
Убрал эс из пауков ужаса.
- …
> Правки пауков ужаса и фелинидов

- Resources/Prototypes/Entities/Objects/Misc/bedsheets.yml
- Resources/Prototypes/_DeadSpace/Entities/Objects/Misc/bedsheets.yml
Изменил слой наложения одеялок в OverDoors на OverMobs. Выполняет ту же задачу, но не закрывает твёрдые объекты.
Надо чинить.
Изменил по одному значению в прототипах односпальных и двухспальных одеялок
Нет
Нет.
:cl:
- fix: Одеяльца теперь не перекрывают твёрдые структуры.
> Фикс слоя наложения одеялок

- Resources/Prototypes/_DeadSpace/Entities/Objects/Tools/tools.yml
- Resources/Prototypes/_DeadSpace/RCD/rcd.yml
Изменение цен РСУ СИ
Хахич попросил
Создана папка прототипа RCD
Не требуется
Нет
:cl:
- tweak: Убрано автовосстановление зарядов у РСУ СИ, теперь вместо этого он использует их меньше для постройки.
> Изменение РСУ СИ

- Resources/Prototypes/_DeadSpace/Entities/Objects/Weapons/Guns/Battery/dominator.yml
Добавлен рефлект проджектайлу доминатора, от него наследуется и снаряду лазерного автомата.
По неизвестной причине эти снаряды не отражались лазерным мечом, щитом и прочим. В угоду логике и баланса было исправлено, наравне с любыми другими энерго-снарядами отражаются.
Изменён прототип летальных снарядов доминатора - Resources/Prototypes/_DeadSpace/Entities/Objects/Weapons/Guns/Battery/dominator.yml
Нет
:cl:
- fix: Заряды доминатора и лазерного автомата теперь исправно отражаются лазерным мечом / щитом.
> Рефлект лазерному автомату и доминатору

- Resources/Prototypes/Maps/Corvax/avrite.yml
- Resources/Prototypes/Maps/Corvax/delta.yml
- Resources/Prototypes/Maps/Corvax/spectrum.yml
По просьбе старшего спрайтера изменил требуемый онлайн двум крупным картам, одной убрал ограничение
По просьбе старшего старшего маппера
Изменены прототипы карт Avrite, Delta, Spectrum
Не требуется
Нет
Думаю не нужно в патчноут добавлять
> Исправление онлайна крупных карт

- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/GameRules/unknown_shuttles.yml
Исправил пиратов - теперь они в пуле вражеских шаттлов и не будут появляться во время гриншифта, Добавил им требование - от 40 минут и от 35 игроков. Взамен сделал спавн мужиков с копьями более частым - от 30 минуты и от 25 игроков. Так же изменил спавн волшебника - от 50 минут и от 30 игроков самостоятельно, раундстартом от 30 игроков - во избежание спавна волшебника на ночной онлайн в 5 человек.
Исправление косяков автора пиратов - теперь они не будут появляться очень рано, на лоупопе и гриншифте. Волшебник же один из сильнейших антагонистов, а требовал всего 10 онлайна и появлялся на 30 минуте регулярно. На баланс не повлияет.
Код изменён не был, изменены значения в оригинальных прототипах официальных разработчиков.
Не требуется.
Нет.
:cl:
- fix: Исправлены …
> Исправление геймрулов пиратов и волшебника

- Resources/Prototypes/_ADT/Customization/Markings/foxtails.yml
Слаймолюды добавлены в вайтлист рас, которые могут использовать лисий хвостик
По предложению https://discord.com/channels/1030160796401016883/1367482145018351626
На баланс не влияет, выглядит хорошо, имеет прозрачность и оттенок тела слаймолюда. Метеоры будут счастливы.
Изменён Resources/Prototypes/_ADT/Customization/Markings/foxtails.yml , добавлен SlimePerson в список допустимых рас.
Нет
:cl:
- tweak: Теперь слаймолюды могут иметь лисий хвостик (Метеор).
> Лисий хвостик метеора доступен слаймолюдам

- Content.Shared/Physics/CollisionGroup.cs
Меняет группы коллизии, чтобы по блобу не могли бегать всякие уроды
Блоб пуся, которого куканят донат расы
Изменено 9 строчек групп коллизий, куда был вставлено коллизия блоба
:cl: no_mad
- fix: Исправлена коллизия блоба
> Фикс коллизии Блоба

- Content.Server/Speech/EntitySystems/ReplacementAccentSystem.cs
Внес изменения к ReplacementAccentSystem. Если верить регексу и логике, то было задумано так, что target не заменяется на replacement, если он внутри слова - т.е декаданс не заменяется на детективаданс (согласно deadspace-chatsan-word-142) из-за этой части в начале регекса поиска слов для замены: "(?<!\w)".
Но в нем не были учтены слова с дефисом (зачастую устойчивые выражения), части которых не должны заменяться.
Поэтому я учел этот момент за оригинальных разработчиков. Под фикс попадают случаи типа "арт-объект", которые теперь не будут заменяться на "артефакт-объект" и т.п.
Изменение не влияет на замену "ар" на "аррр" и подобного у некоторых рас внутри составных слов.
Чтобы части экспрессивных выражений не заменялись акцентом. Например, художественное и экспрессивное ни-че-го или …
> Фикс коррекции речи

- Resources/Prototypes/_DeadSpace/Spiders/spiders.yml
Добавил два компонента иммунитета базовому прототипу пауков ужаса. Одобрено KloopRee.
Зомбированные пауки ужаса очень сильны, обладают всеми способностями и возможностью эволюционировать, что уберёт заражение. Во благо баланса.
В прототип BaseMobSpiderTerror добавлены два компонента иммунитета - ZombieImmune и ImmunitetInfectionDead
Не надо
Нет
:cl:
- tweak: Теперь пауки ужаса обладают иммунитетом к зомби и некро вирусам.
> Иммунитет от зомби и некро паучкам жужаса

- Content.Server/DeadSpace/Abilities/StanRadius/StanRadiusSystem.cs
- Content.Shared/DeadSpace/Abilities/StunRadius/Components/StunRadiusComponent.cs
Убран стан борга криком паука
Основано на: https://discord.com/channels/1030160796401016883/1138194012575113297/threads/1377598561960726568
Логично
Добавил поле StunBorg в StunRadiusComponent, изначально false, которое определяет, надо ли станить боргов этой абилкой.
Фикс распространяется и на стан пауками, и демоном-клоуном (если надо, чтобы демон станил боргов, можно подредачить у них в ymlке. Я подумал, что они тоже не должны станить боргов)
Не
Не
:cl:
- tweak: Убран стан боргов криком пауков
> Убран стан борга криком паука

- Resources/Prototypes/_DeadSpace/Spiders/antag.yml
- Resources/Prototypes/_DeadSpace/Spiders/spiders.yml
Убрал возможность перезарядить паука дрона и достать ключ шифрования Пауков Ужаса. Вставление себе в гарнитуру не убирал, так как получить ключ всё равно нельзя.
Странно, поэтому убрал. 
Добавил строчку cycleable: false чтобы заблокировать кнопку "Перезарядить" и заблокировал ключ шифрования у связующей паутины чтобы его нельзя было извлечь. Разрушение связующей паутины или её подрыв ключ не извлекают, как и все типы инструментов.
Не надо.
Нету
:cl:
- fix: Паука дрона больше нельзя перезарядить, а из связующей паутины извлечь ключ шифрования Пауков Ужаса.
> Фикс паука дрона и связующей паутины

- Resources/Prototypes/_Corvax/Entities/Mobs/NPCs/pets.yml
Добавил DoorBumpOpener, который почему-то потерялся в PR-е на Ларго
Исправление косяка
Добавил тэг DoorBumpOpener
Не надо
Нет
:cl:
- fix: Ларго научили пользоваться шлюзами - теперь он может их открывать.
> Хотфикс Ларго

- Resources/Prototypes/Catalog/Fills/Crates/service.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
- Resources/Prototypes/Loadouts/Miscellaneous/survival.yml
- Resources/Prototypes/_DeadSpace/Entities/Objects/Consumable/Food/snacks.yml
Исправил появление обычной аварийной коробки у молей, убрал возможность молькам кушать обёртки.
Исправил свой же косяк. Возможность кушать обёртки убрал нианам за ненадобностью - это был костыль разработчиков, ещё и довольно питательный.
Удалён тэг еды из ткани у обёрток в /Entities/Objects/Consumable/Food/snacks.yml и /_DeadSpace/Entities/Objects/Consumable/Food/snacks.yml, удалены нианы из списка выдачи обычных аварийных наборов тут /Loadouts/Miscellaneous/survival.yml
Не требуется
Нет
:cl:
- tweak: Нианы теперь не могут кушать обёртки от ИРП и ВРП.
- fix: Исправлена выдача обычного аварийного набора нианам.
> Исправление аварийного лоадаута молей и обёрток от ВРП/ИРП

- Resources/Prototypes/_DeadSpace/Entities/Objects/Specific/Robotics/borg_modules.yml
- Resources/Prototypes/_DeadSpace/security_borg.yml
Исправил отображение спрайтов в руках у всех модулей борга СБ и у своих шахтёрских модулей, теперь нет большой еррорки в руках.
Исправление под обновление остальных модулей
Изменены прототипы в _DeadSpace/security_borg.yml и _DeadSpace/Entities/Objects/Specific/Robotics/borg_modules.yml, использованы стандартные спрайты, чтобы не плодить лишние файлы
Нет
:cl:
- fix: Исправлено отображение в руках модулей борга СБ, утилизаторского оружейного и продвинутого шахтёрского.
> Исправление отображения модулей борга в руках

- Resources/Prototypes/_ADT/Entities/Objects/Consumable/Food/shawerma.yml
Добавил тэг Meat базовой шаурме - теперь все плотоядные расы могут ею питаться
Исправление недоработки, по просьбам в предложке и багах. На баланс не влияет
Добавил компонент Tag и сам тэг Meat в прототипе _ADT/Entities/Objects/Consumable/Food/shawerma.yml
Не требуется
Нет
:cl:
- fix: Теперь все плотоядные расы могут кушать шаурму.
> Исправление шавухи

- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Доступ к одобрению заказов есть только у глав (и смотрителя). 
Обычные сотрудники станции заказывают всё подряд, что негативно сказывается на работе карго. По аналогии с обычной консолью заказов карго (снабжение -> квартирмейстер) доступы были заменены для более ответственного подхода. Консоли заказа СБ сделаны доступы оружейной, чтобы смотритель мог сам заказать необходимое для работы брига. На баланс не влияет.
Изменены доступы в Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Не требуется
Нет
:cl:
- tweak: Теперь консоли заказов отделов требуют доступ главы. В СБ требуется доступ оружейной.
> Доступы к консолям заказа у глав

- Resources/Prototypes/_ADT/Recipes/Cooking/croissant_recipe.yml
- Resources/Prototypes/_ADT/Recipes/Cooking/fried_egg_recipe.yml
- Resources/Prototypes/_ADT/Recipes/Cooking/sausage_recipe.yml
- Resources/Prototypes/_ADT/Recipes/Cooking/shawerma_recipe.yml
- Resources/Prototypes/_Corvax/Recipes/Cooking/meat_recipes.yml
- Resources/Prototypes/_DeadSpace/Recipes/Cooking/meal_recipes.yml
Прописал группы всем кастомным (корвакс, адт, дедспейс) рецептам, чтобы они корректно отображались в соответствующей категории рецептов блюд в гайдбуке. Попутно обновил рецепт круассанов, добавив вместо теста - сырой круассан (рецепт делали когда такого ещё не изобрели оффы)
Правки старых рецептов для большей актуальности. На баланс не влияет
Затронул все рецепты вне пространства оффов, не помечал # DS14 (но могу)
Не требуется
Нет
:cl:
- tweak: Изменены рецепты сливочного, шоколадного и сырного круассанов.
> Группы кастомным рецептам еды, обновление рецепта круассанов

- Content.Client/Cargo/UI/CargoBountyMenu.xaml
- Content.Client/Cargo/UI/CargoConsoleMenu.xaml
- Content.Client/CloningConsole/UI/CloningConsoleWindow.xaml
- Content.Client/Instruments/UI/InstrumentMenu.xaml
- Content.Client/Instruments/UI/InstrumentMenu.xaml.cs
- Content.Client/Research/UI/ResearchConsoleMenu.xaml
- Content.Client/Salvage/UI/SalvageJobBoardMenu.xaml
В апстриме менялись многие консоли, из-за локализации много где теперь не помещается текст и выглядит NE OCHE. Расширил интерфейс до нужного размера, чтобы всё было хорошо. Переделал интерфейс музыкальных инструментов заодно.
Конкретика:
Консоль клонирования была обновлена, но изначальное окошко крохотное и не помещает текст
Исследовательская консоль кушала названия технологий, названия веток
Консоль заказов утилизаторов имела крохотное окошко, где текст на кнопках больше самих кнопок
Консоли заказов не показывали кнопки из-за длины названий товаров
Музыкальные инструменты уже сто лет имеют кривой интерфейс, где кнопочки выглядят не красиво. Тут сделал иначе и пересобрал интерфейс, чтобы это выглядело компактно, красиво (внутренний перфекционист доволен) и не слишком громоздко. Тут …
> Расширение UI новых/обновлённых консолей, перестановка в UI музыкальных инструментов
